[general]
context=default

[1000]
type=friend
secret=1234
host=dynamic
context=default

[1001]
type=friend
secret=1234
host=dynamic
context=default

[1002]
type=friend
secret=1234
host=dynamic
context=default
